// flow-typed signature: 1e095535e8e414790409e61f2d2c8f74
// flow-typed version: <<STUB>>/imagemin-mozjpeg_v^7.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'imagemin-mozjpeg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'imagemin-mozjpeg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'imagemin-mozjpeg/index' {
  declare module.exports: $Exports<'imagemin-mozjpeg'>;
}
declare module 'imagemin-mozjpeg/index.js' {
  declare module.exports: $Exports<'imagemin-mozjpeg'>;
}
